/*
 * Copyright (C) 2026-present ScyllaDB
 */

/*
 * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1
 */

//
// Makes a real S3 endpoint answer "503 SlowDown" and checks that the write path
// copes with it.
//
// The load is generated by writing many small sstables at once and then
// unlinking them, i.e. through sstables::storage - the abstraction that both
// filesystem_storage and s3_storage implement. Nothing here mentions S3 beyond
// the storage options handed to test_env, so the test keeps exercising the same
// code path if throttling handling is later added underneath, and it can be
// pointed at local storage unchanged.
//
// The write path is what makes throttling reproducible. PUT/COPY/POST/DELETE
// share a per-prefix request budget appreciably lower than the one for GET/HEAD,
// and what counts is the arrival rate rather than the completion rate. Reads
// were tried first and do not work for this: two million HEADs over eight
// minutes against the same prefix produced zero throttling statuses, S3 answered
// those by closing connections instead.
//
// Throttling is observed by tapping the stream seastar logs to.
// aws::default_aws_retry_strategy reports every retry together with the message
// the server sent, so no production code has to change to see this.
//
// Needs a real bucket and credentials, so it is skipped unless
// ENABLE_S3_SLOWDOWN_TEST is set:
//
//   export S3_SERVER_ADDRESS_FOR_TEST=s3.eu-central-1.amazonaws.com
//   export S3_SERVER_PORT_FOR_TEST=443
//   export S3_BUCKET_FOR_TEST=my-bucket
//   export AWS_DEFAULT_REGION=eu-central-1
//   export AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=...
//   export ENABLE_S3_SLOWDOWN_TEST=1
//
// Optional knobs: S3_SLOWDOWN_SSTABLES (default 4000),
// S3_SLOWDOWN_CONCURRENCY (default 512).
//

#include <chrono>
#include <cstdlib>
#include <iostream>
#include <mutex>
#include <ostream>
#include <ranges>
#include <streambuf>
#include <string>
#include <string_view>
#include <vector>

#include <boost/test/unit_test.hpp>

#include <seastar/core/coroutine.hh>
#include <seastar/core/loop.hh>
#include <seastar/util/log.hh>

#include "mutation/mutation.hh"
#include "mutation/timestamp.hh"
#include "schema/schema_builder.hh"
#include "sstables/sstables.hh"
#include "sstables/version.hh"
#include "test/lib/log.hh"
#include "test/lib/scylla_test_case.hh"
#include "test/lib/sstable_test_env.hh"
#include "test/lib/sstable_utils.hh"
#include "test/lib/test_utils.hh"
#include "types/types.hh"
#include "utils/chunked_vector.hh"

using namespace seastar;
using namespace sstables;

namespace {

// Counts retries, and how many of them were the endpoint telling us to slow
// down, by watching the lines aws::default_aws_retry_strategy logs. That log
// carries the <Message> the server sent rather than the <Code>, so the match is
// on the message text.
//
// Lines are forwarded to the original stream, so the run stays readable. The
// mutex is needed because seastar logs from whichever shard produced the line.
class throttling_probe {
public:
    struct counters {
        uint64_t retries = 0;
        uint64_t throttled = 0;
    };

private:
    class tap final : public std::streambuf {
        std::streambuf* _next;
        std::mutex _mu;
        std::string _line;
        counters _counters;

        void classify(const std::string& line) {
            if (!line.contains("AWS HTTP client request failed")) {
                return;
            }
            ++_counters.retries;
            // "Please reduce your request rate." is what S3 sends with
            // <Code>SlowDown</Code>; the rest cover the other throttling codes
            // and endpoints that word it differently.
            for (std::string_view needle : {"reduce your request rate", "SlowDown",
                                            "Service Unavailable", "Too Many Requests",
                                            "Throttl"}) {
                if (line.contains(needle)) {
                    ++_counters.throttled;
                    return;
                }
            }
        }

        void consume(const char* s, std::streamsize n) {
            auto lock = std::lock_guard(_mu);
            for (std::streamsize i = 0; i < n; i++) {
                if (s[i] == '\n') {
                    classify(_line);
                    _line.clear();
                } else {
                    _line.push_back(s[i]);
                }
            }
        }

    public:
        explicit tap(std::streambuf* next) noexcept : _next(next) {}

        counters get_counters() {
            auto lock = std::lock_guard(_mu);
            return _counters;
        }

    protected:
        int_type overflow(int_type ch) override {
            if (traits_type::eq_int_type(ch, traits_type::eof())) {
                return traits_type::not_eof(ch);
            }
            auto c = traits_type::to_char_type(ch);
            consume(&c, 1);
            return _next->sputc(c);
        }

        std::streamsize xsputn(const char_type* s, std::streamsize n) override {
            consume(s, n);
            return _next->sputn(s, n);
        }

        int sync() override { return _next->pubsync(); }
    };

    tap _tap;
    std::ostream _out;

public:
    throttling_probe() : _tap(std::cerr.rdbuf()), _out(&_tap) {
        seastar::logger::set_ostream(_out);
    }
    ~throttling_probe() { seastar::logger::set_ostream(std::cerr); }

    throttling_probe(const throttling_probe&) = delete;
    throttling_probe& operator=(const throttling_probe&) = delete;

    counters snapshot() { return _tap.get_counters(); }
};

unsigned env_uint(std::string_view name, unsigned def) {
    auto v = tests::getenv_or_default(name);
    if (v.empty()) {
        return def;
    }
    try {
        return static_cast<unsigned>(std::stoul(v));
    } catch (const std::exception&) {
        testlog.warn("{} is not a number ('{}'), using default {}", name, v, def);
        return def;
    }
}

// Runs func() count times, `concurrency` at a time, and returns how many threw.
// Exceptions are counted rather than propagated: once retries are exhausted, a
// throttled request is expected to fail.
uint64_t run_concurrently(unsigned count, unsigned concurrency,
        noncopyable_function<future<> (unsigned)> func) {
    uint64_t failures = 0;
    // Named, because max_concurrent_for_each() requires the range to outlive
    // the call.
    auto indexes = std::views::iota(0u, count);
    max_concurrent_for_each(indexes, concurrency, [&] (unsigned i) -> future<> {
        try {
            co_await func(i);
        } catch (...) {
            ++failures;
        }
    }).get();
    return failures;
}

void report(std::string_view phase, unsigned done, unsigned total,
        std::chrono::steady_clock::duration elapsed, const throttling_probe::counters& c) {
    auto secs = std::chrono::duration<double>(elapsed).count();
    testlog.info("{}: {} of {} sstables in {:.1f}s = {:.0f}/s, {} retries "
                 "({} of them the endpoint asking us to slow down)",
            phase, done, total, secs, secs > 0 ? done / secs : 0.0, c.retries, c.throttled);
}

} // anonymous namespace

SEASTAR_TEST_CASE(s3_slowdown_write_storm,
        *tests::check_run_test_decorator("ENABLE_S3_SLOWDOWN_TEST", false)) {
    const auto count = env_uint("S3_SLOWDOWN_SSTABLES", 4000);
    const auto concurrency = env_uint("S3_SLOWDOWN_CONCURRENCY", 512);
    return test_env::do_with_async([count, concurrency] (test_env& env) {
        auto s = schema_builder(this_smp_shard_count(), "ks", "s3_slowdown")
                .with_column("pk", int32_type, column_kind::partition_key)
                .with_column("v", int32_type)
                .build();

        // One tiny partition per sstable: the point is the number of objects
        // created, not their size. Each sstable is a handful of components, so
        // each write is a handful of requests.
        auto make_mutation = [&] (int32_t k) {
            auto pk = partition_key::from_single_value(*s, int32_type->decompose(k));
            mutation m(s, pk);
            m.set_clustered_cell(clustering_key::make_empty(), *s->get_column_definition("v"),
                    atomic_cell::make_live(*int32_type, api::new_timestamp(),
                            int32_type->decompose(k)));
            return m;
        };

        throttling_probe probe;
        testlog.info("writing {} sstables with concurrency {}", count, concurrency);

        std::vector<shared_sstable> written(count);
        auto t0 = std::chrono::steady_clock::now();
        auto write_failures = run_concurrently(count, concurrency, [&] (unsigned i) -> future<> {
            utils::chunked_vector<mutation> muts;
            muts.push_back(make_mutation(int32_t(i)));
            written[i] = co_await make_sstable_containing(
                    env.make_sst_factory(s, sstable_version_types::mt), std::move(muts));
        });
        auto write_elapsed = std::chrono::steady_clock::now() - t0;
        auto after_write = probe.snapshot();
        report("write", count - write_failures, count, write_elapsed, after_write);

        // Remove what got written, again through sstables::storage. This is the
        // cleanup: without it the objects would be left behind. Note that for
        // object storage unlink() returns well before the objects are actually
        // gone - the removal continues in the background and finishes while the
        // env shuts down - so no rate is reported for it and the verdict below
        // only covers the write phase.
        auto unlink_failures = run_concurrently(count, concurrency, [&] (unsigned i) -> future<> {
            if (written[i]) {
                co_await written[i]->unlink();
            }
        });
        testlog.info("cleanup: {} of {} sstables unlinked", count - unlink_failures, count);

        // Whether the endpoint throttles depends on the bucket's history and its
        // current limit, so this is reported rather than asserted.
        if (after_write.throttled) {
            testlog.info("verdict: endpoint returned {} throttling statuses out of {} retries",
                    after_write.throttled, after_write.retries);
        } else {
            testlog.info("verdict: no throttling status seen ({} retries for other reasons). "
                         "Raise S3_SLOWDOWN_CONCURRENCY or S3_SLOWDOWN_SSTABLES, or use a "
                         "bucket whose prefix has not been warmed up.", after_write.retries);
        }
        // What is asserted is that throttling does not turn into a total loss:
        // the retry path has to get most of the work through, and the cleanup
        // has to remove what was created.
        BOOST_REQUIRE_LT(write_failures, count);
        BOOST_REQUIRE_EQUAL(unlink_failures, 0);
    }, test_env_config {
        .storage = make_test_object_storage_options("S3"),
        .object_storage_max_connections = concurrency,
    });
}
